name: Create release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get changelog entry
        id: changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          version: "$RELEASE_VERSION"
          path: ./CHANGELOG.md
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "$RELEASE_VERSION"
          release_name: "$RELEASE_VERSION"
          body: ${{ steps.changelog.outputs.changes }}
          prerelease: ${{ steps.changelog.outputs.status == 'prereleased' }}
          draft: ${{ steps.changelog.outputs.status == 'unreleased' }}
